query ListBlogs {
  blogs {
    title
    content
    author {
      username
    }
  }
}

query GetBlog($id: Float!) {
  getBlog(id: $id) {
    title
    content
  }
}

query ListUsers {
  users {
    username
    password
  }
}

query GetUser($id: Float!) {
  getUser(id: $id) {
    username
    blogs {
      title
    }
  }
}