query ListBlogs {
  blogs {
    title
    content
    author {
      username
    }
  }
}

query GetBlog($id: Float!) {
  getBlog(id: $id) {
    title
    content
  }
}

query ListUsers {
  users {
    username
    password
  }
}

query GetUser($id: Float!) {
  getUser(id: $id) {
    username
    blogs {
      title
    }
  }
}

mutation CreateBlog($title: String!, $content: String!, $authorId: Float!) {
  createBlog(title: $title, content: $content, authorId: $authorId) {
    title
  }
}

mutation SignIn($username: String!, $password: String!) {
  signin(username: $username, password: $password) {
    token 
  }
}
